# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Slauth
version:      0.01
version_from: lib/Slauth.pm
installdirs:  site
requires:
    CGI:                           3
    CGI::Carp:                     1.28
    CGI::Cookie:                   1.24
    Digest::MD5:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
